Feature/ids transaction transfer
starkbank/sdk-ruby pull request #14
Opened 2020-09-14 15:30 UTC by vidalstark

2020-09-14 18:16 UTC, cdottori-stark requested changes

2020-09-14 18:16 UTC, cdottori-stark commented on CHANGELOG.md
> +- ids parameter to transfer.query
`Transaction.query` & `Transfer.query`

2020-09-14 19:01 UTC, vidalstark commented on CHANGELOG.md
> +- ids parameter to transfer.query
Done

2020-09-15 12:42 UTC, cdottori-stark approved these changes

2020-09-15 12:43 UTC, merged