Add page method to resources
starkbank/sdk-ruby pull request #36
Opened 2021-07-28 22:06 UTC by massaru-stark

2021-07-28 22:11 UTC, cdottori-stark requested changes

2021-07-28 22:11 UTC, cdottori-stark commented on lib/boleto/boleto.rb
> +    # - user [Organization/Project object]: Organization or Project object. Not necessary if Starkbank.user was set before function call
Starkbank com b minúsculo de novo, melhor dar um find all e trocar logo tudo

2021-07-28 22:11 UTC, cdottori-stark commented on lib/utils/rest.rb
>        def self.get_list(resource_name:, resource_maker:, user: nil, **query)
acho que tem trocar o get_list pra get_stream, nao?

2021-07-28 22:11 UTC, cdottori-stark commented on test/starkbank/test_boleto.rb
> +
Tudo certo com o teste, mas faltou README e CHANGELOG no PR

2021-07-29 15:48 UTC, cdottori-stark requested changes

2021-07-29 15:48 UTC, cdottori-stark commented on README.md
> +
linha a mais

2021-07-29 15:48 UTC, cdottori-stark commented on lib/boleto/log.rb
> +      # - before [Date, DateTime, Time or string, default nil] date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
faltou o ":" aqui no "default nil]:"

2021-07-29 15:48 UTC, cdottori-stark commented on lib/boleto/log.rb
> +      # - after [Date, DateTime, Time or string, default nil] date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
faltou o ":" aqui no "default nil]:"

2021-07-29 15:48 UTC, cdottori-stark commented on lib/boleto/log.rb
> +      # - before [Date, DateTime, Time or string, default nil] date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
Parece que rolou em outros lugares no after e no before, confere?

2021-07-29 15:48 UTC, cdottori-stark commented on lib/boleto/log.rb
> +      # - list of Log objects with updated attributes and cursor to retrieve the next page of Boleto objects
next page of Log objects

2021-07-29 15:48 UTC, cdottori-stark commented on lib/boleto_holmes/log.rb
> +      # - list of Log objects with updated attributes and cursor to retrieve the next page of Boleto objects
Acho que esse next page of Boletos ta errado em vários lugares, mas só vou comentar mais esse ok?

2021-07-29 15:48 UTC, cdottori-stark commented on lib/boleto_holmes/log.rb
> +      # - list of Log objects with updated attributes and cursor to retrieve the next page of Boleto objects
Da um cmmd+shift+f "the next page of Boleto objects" pra ver onde ficou errado

2021-07-29 15:48 UTC, cdottori-stark commented on lib/brcode_preview/brcode_preview.rb
> +    # - user [Organization/Project object]: Organization or Project object. Not necessary if StarkBank.user was set before function call
só nas docstrings de query que tava errado? no resto todo tava certo?

2021-07-29 15:48 UTC, cdottori-stark commented on test/starkbank/test_webhook.rb
> +    expect(ids.length).must_equal(10)
ta quebrando isso nao? em geral acho que a gente tava colocando <= 10 pra não quebrar nesse caso

2021-07-29 16:36 UTC, massaru-stark commented on lib/brcode_preview/brcode_preview.rb
> +    # - user [Organization/Project object]: Organization or Project object. Not necessary if StarkBank.user was set before function call
Sim

2021-07-29 16:41 UTC, massaru-stark commented on test/starkbank/test_webhook.rb
> +    expect(ids.length).must_equal(10)
Não quebrou

2021-07-29 18:44 UTC, cdottori-stark approved these changes

2021-07-29 18:44 UTC, merged